### ISSUE TITLE
Maven-Plugin generates empty Deployment selector value in kubernetes.yml

### ISSUE THREAD

**Issue by thlaegler** [fabric8io/fabric8-maven-plugin#1021]
### Description

Although we disabled ALL enrichers and ALL generators, the fabric8-maven-plugin adds "spec.selector: {}" (with empty curly brackets) to the target Kubernetes List (kubernetes.yml) and then cries about "empty selector is not valid for deployment".
We use the generated aggregated kubernetes.yml (`<targetDir>${project.build.directory}/fabric8</targetDir>`)

### Info

* f-m-p version : 3.5.22
* Maven version : 3.3.9
* Sample project : https://github.com/thlaegler/fabric8-example (`mvn clean install`)

### Example

Given fragment: src/main/fabric8/fabric8-example-deployment.yaml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fabric8-example
  namespace: services
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fabric8-example
    spec:
      containers:
      - name: fabric8-example
        image: fabric8-example:0.0.1-SNAPSHOT
        ports:
        - name: rest
          containerPort: 8888
```

Actual result after `mvn clean install` or `mvn fabric8:resource`  the file target/fabric8/kubernetes.yml (generated aggregated target Deployment List) looks like this:
```
---
apiVersion: v1
kind: List
items:
[...]
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: fabric8-example
    namespace: services
  spec:
    replicas: 1
    selector: {} <-- * unwanted/unexpected/causing error *
    template:
      metadata:
        labels:
          app: fabric8-example
      spec:
        containers:
          image: fabric8-example:0.0.1-SNAPSHOT
          name: fabric8-example
          ports:
          - containerPort: 8888
            name: rest
[...]
```

Expected result: the aggregated kubernetes.yml should not have a selector or not have an empty selector-list.

The same issue applies also for the generated helm-deployment-yaml (target/fabric8/helm/kubernetes/fabric8-example/templates/fabric8-example-deployment.yaml). Strange is also, that helm chart and helm deployment files are only generated when `<targetDir>` is NOT customized/set. We can either customize the `<targetDir>` and get a (not usable) kubernetes.yml but NO helm chart OR we don't customize the `<targetDir>` and get a helm chart, but NO kubernetes.yml.
