### ISSUE TITLE
Do not add ImageChange change triggers for Docker images

### ISSUE THREAD

**Issue by nicolaferraro** [fabric8io/fabric8-maven-plugin#1037]
When using a docker image without image stream for a container in Openshift (e.g. to deploy a sidecar) in the `src/main/fabric8/deployment.yml` file ([example here](https://github.com/kevinearls/jaeger-performance-tests/blob/0ae14ca38ac1779967f4d808eff9c6dc96f0ab0e/spring-boot/src/main/fabric8/deployment.yml#L5-L19)), the plugin adds a triggers  on ImageStreamTag change, but there's no image stream since we want to use the docker image directly.

Fragment of the generated yml.
```
...
    triggers:
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jaeger-agent
        from:
          kind: ImageStreamTag
          name: jaeger-agent:latest
```

In this case the docker image is `jaegertracing/jaeger-agent:latest`. We should detect if a container image is a IS or a Docker image and add triggers in the first case only.
