### ISSUE TITLE
Specifying a generated parameter in the template

### ISSUE THREAD

**Issue by vcottagiri** [fabric8io/fabric8-maven-plugin#1057]
What is the way to specify in f-m-p that a parameter value will be generated by openshift during deployment? Please see [this link](https://docs.openshift.org/latest/dev_guide/templates.html#writing-templates) on the generate directive for parameters.

```
parameters:
- description: Password used for Redis authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: REDIS_PASSWORD
```

f-m-p version : 3.5.30
Maven version : 3.5.0
