### ISSUE TITLE
VolumeMounts in deployment.yml breaks `fabric8:resource` 

### ISSUE THREAD

**Issue by hazim1093** [fabric8io/fabric8-maven-plugin#1099]
### Description

Adding volume mount in `deployment.yml` for my springboot project, results in the following error while running `mvn fabric:resource`  : 
```
Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.31:resource (default-cli) on project gatewayapi: 
Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.5.31:resource failed:
Container null has no Docker image configured. Please check your Docker image configuration (including the generators which are supposed to run)
```

I found out that this error is part of the Openshift converter (https://github.com/fabric8io/fabric8-maven-plugin/blob/master/plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java) 

I don't need openshift files to be generated as I'm using kubernetes, so i added this to `pom.xml`  but no still no luck:
 ```
<fabric8.mode>kubernetes</fabric8.mode>
```

### Info

f-m-p version : 3.5.31
Maven version (mvn -v) : 3.3.9
Kubernetes version : Kubernetes v1.7.8

### Steps to reproduce
1. Create a `deployment.yml` in `src/main/fabric8`
```
spec:
  template:
    spec:
      containers:
        - env:
            - name: MY_VAR
              value: hello
        - volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket

```

2. Run `mvn fabric8:resource`. 

The target will fail while generating openshift files

**Comment by hazim1093** [comment]
Hi, @ro14nd @nicolaferraro 
Any idea about this issue? or about adding volume mounts to `deployment.yml`?

**Comment by nicolaferraro** [comment]
Hi @hazim1093, it seems there's a error in your `deployment.yml` file. You have accidentally declared 2 containers with a dash (`-`) before `volumeMounts`.

This one should work (resources should be generated, but I don't know if you need additional security grants to be allowed to mount `/var/run/docker.sock`):

```
spec:
  template:
    spec:
      containers:
        - env:
            - name: MY_VAR
              value: hello
          volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
```
