### ISSUE TITLE
InitContainers when defined within DeploymentConfig are removed from final resource created and deployed

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-maven-plugin#1114]
When a pod to be deployed includes within its `DeploymentConfig` spec yaml file initContainers, then they are skipped when f-m-p (3.5.30) process them

The original `dc.yaml` file containing 2 initcontainers and 2 containers

```
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: helloworld
spec:
  template:
    spec:
      containers:
        - image: istio/examples-helloworld-v1
          imagePullPolicy: IfNotPresent
          name: helloworld
          ports:
            - containerPort: 5000
              protocol: TCP

        - image: 'docker.io/istio/proxy_debug:0.2.12'
          imagePullPolicy: IfNotPresent
          name: istio-proxy
          resources: {}
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 1337
      initContainers:
        - args:
            - '-p'
            - '15001'
            - '-u'
            - '1337'
          image: 'docker.io/istio/proxy_init:0.2.12'
          imagePullPolicy: IfNotPresent
          name: istio-init
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
            - '-c'
            - >-
              sysctl -w kernel.core_pattern=/etc/istio/proxy/core.%e.%p.%t &&
              ulimit -c unlimited
          command:
            - /bin/sh
          image: alpine
          imagePullPolicy: IfNotPresent
          name: enable-core-dump
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: '0'
          name: istio-envoy
        - name: istio-certs
          secret:
            defaultMode: 420
            optional: true
            secretName: istio.default
```
and if deployed correctly we should see such info

![screenshot 2017-11-29 15 18 53](https://user-images.githubusercontent.com/463790/33380769-731ac914-d51c-11e7-86a7-9a1d97f80bef.png)

but this is not the case.

The file `oc.yaml` generated only contain 2 containers and not initContainers

```
---
apiVersion: v1
kind: DeploymentConfig
spec:
  template:
    metadata:
    spec:
      containers:
        image: istio/examples-helloworld-v1
        imagePullPolicy: IfNotPresent
        name: helloworld
        ports:
        - containerPort: 5000
          name: commplex-main
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log

        image: docker.io/istio/proxy_debug:0.2.12
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        resources: {}
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          runAsUser: 1337
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: istio-certs
        secret:
          defaultMode: 420
          secretName: istio.default
```
![screenshot 2017-11-29 15 53 45](https://user-images.githubusercontent.com/463790/33381219-a90333c6-d51d-11e7-80ed-305522747ba7.png)

When looking to the code, it appears that we don't during enrichment append initContainers excepted for Volume, TLS

![screenshot 2017-11-29 14 57 06](https://user-images.githubusercontent.com/463790/33380934-e6233c8e-d51c-11e7-97f5-6f8ac48043c0.png)
