### ISSUE TITLE
looks like the generated openshift.yml has duplicate resources

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#119]
I get 2 Service and 2 DC objects:
```
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      fabric8.io/iconUrl: "data:text/plain;charset=UTF-8;base64,cm91dGVzLnhtbAo="
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      project: "springboot-camel-xml"
      provider: "fabric8"
      version: "1.0-SNAPSHOT"
      group: "io.fabric8.quickstarts"
    name: "springboot-camel-xml"
  spec:
    ports:
    - port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "springboot-camel-xml"
      provider: "fabric8"
      group: "io.fabric8.quickstarts"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      fabric8.io/iconUrl: "data:text/plain;charset=UTF-8;base64,cm91dGVzLnhtbAo="
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      project: "springboot-camel-xml"
      provider: "fabric8"
      version: "1.0-SNAPSHOT"
      group: "io.fabric8.quickstarts"
    name: "springboot-camel-xml"
  spec:
    ports:
    - port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "springboot-camel-xml"
      provider: "fabric8"
      group: "io.fabric8.quickstarts"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/camel.svg"
      fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=springboot-camel-xml&var-version=1.0-SNAPSHOT"
    labels:
      project: "springboot-camel-xml"
      provider: "fabric8"
      version: "1.0-SNAPSHOT"
      group: "io.fabric8.quickstarts"
    name: "springboot-camel-xml"
  spec:
    replicas: 1
    selector:
      project: "springboot-camel-xml"
      provider: "fabric8"
      group: "io.fabric8.quickstarts"
    template:
      metadata:
        labels:
          project: "springboot-camel-xml"
          provider: "fabric8"
          version: "1.0-SNAPSHOT"
          group: "io.fabric8.quickstarts"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "quickstarts/springboot-camel-xml:latest"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 180
          name: "springboot"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          - containerPort: 9779
            protocol: "TCP"
          - containerPort: 8778
            protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: "ConfigChange"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/camel.svg"
      fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=springboot-camel-xml&var-version=1.0-SNAPSHOT"
    labels:
      project: "springboot-camel-xml"
      provider: "fabric8"
      version: "1.0-SNAPSHOT"
      group: "io.fabric8.quickstarts"
    name: "springboot-camel-xml"
  spec:
    replicas: 1
    selector:
      project: "springboot-camel-xml"
      provider: "fabric8"
      group: "io.fabric8.quickstarts"
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/camel.svg"
          fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=springboot-camel-xml&var-version=1.0-SNAPSHOT"
        labels:
          project: "springboot-camel-xml"
          provider: "fabric8"
          version: "1.0-SNAPSHOT"
          group: "io.fabric8.quickstarts"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "quickstarts/springboot-camel-xml:latest"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 180
          name: "springboot"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          - containerPort: 9779
            protocol: "TCP"
          - containerPort: 8778
            protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: "ConfigChange"
kind: "List"

```
