### ISSUE TITLE
Kedge integration

### ISSUE THREAD

**Issue by containscafeine** [fabric8io/fabric8-maven-plugin#1210]
@piyush1594 creating this so this does not slip out of our minds. Can you please update with our discussion from yesterday.

**Comment by piyush1594** [comment]
Right now, we are supporting resource fragments where the user can mention their extra requirements and we override default values by those requirements during the resource generation stage.

Similarly, we can add the integration of Kedge. By doing this, the user can specify Kedge, here not as extra requirements but the overall requirements. Then we can use `Kedge generate` command to generate the kubernetes and openShift resources. If a user specifies a Kedge file, we will replace the resource stage by `kedge generate` command.

Right now, somewhat similar is done using Kompose, a user can specify the docker-compose file and we use Kompose to generate kubernetes yaml.

Comments welcome @containscafeine @hrishin @surajnarwade @tkral @surajssd 

@hrishin Please correct if I am wrong in the concept.

**Comment by containscafeine** [comment]
@piyush1594 I agree with the overall idea :+1: how do we prioritize this? This is a huge bump in user experience with not a lot effort because we simply have to shell out to a binary. ping @pradeepto

**Comment by rohanKanojia** [comment]
@hrishin @nicolaferraro @rhuss: Thoughts????????

**Comment by rhuss** [comment]
Sorry, haven't looked yet at Kedge, but could please someone briefly summarize the difference between Kedge and Kompose (as we already have Kompose support ?)

**Comment by hrishin** [comment]
Kedge tries to simplify writing an application definition using kubernetes native structs. It takes kedgefile as input which has minimalistic  specification of deployment, service etc. and generates a full blown yaml resources as a output. (kind of defining partial resource fagments as we do in FMP but its more simplified) 

http://kedgeproject.org

> could please someone briefly summarize the difference between Kedge and Kompose (as we already have Kompose support ?)

Kompose translates docker compose file to kubernetes resources file. While Kedge tries to simplify writing kubernetes resource yaml. 

@surajnarwade @surajssd @piyush1594 feel please add/correct if something is missing here.

**Comment by surajssd** [comment]
So kedge has it's own way of defining kubernetes app, which is a re-structured version of what you will define in things like Deployment, Service, etc.

Here is an example of one:
http://kedgeproject.org/file-reference/

```yaml
name: httpd

deployments:
- containers:
  - image: centos/httpd

services:
- name: httpd
  type: LoadBalancer
  portMappings: 
    - 8080:80
```

which gets converted to 

```console
$ kedge apply -f httpd.yaml
deployment "httpd" created
service "httpd" created
```

**Comment by containscafeine** [comment]
Worth checking if the project is still actively maintained :)

**Comment by rhuss** [comment]
@surajssd but isn't [kompose](https://github.com/kubernetes/kompose) similar in that respect as it uses plain docker-compose.yml files and creates the appropriate k8s resources ?

So that you can use the simplified compose syntax to create full blow resource descriptors ?

I wonder what the real difference or benefit of kedge over kompose is ...

A kompose file looks like

```yaml
services:

 web:
  image: tuna/docker-counter23
  ports:
    - "5000:5000"
  deploy:
    replicas: 1
    restart_policy:
      condition: any
  labels:
    kompose.service.type: NodePort

 redis:
  image: redis:3.0
  ports:
    - "6379"
```

So it provides maybe an even higher abstraction (abstracting away deployments & service behind one kedge service).

Is there any other difference ?
