### ISSUE TITLE
Q: how to set container mem and cpu limits?

### ISSUE THREAD

**Issue by magick93** [fabric8io/fabric8-maven-plugin#1256]
Hello

Apologies if this is not the correct place to ask such questions.

Im using f8 maven plugin version 2.3.7.

Currently when I deploy, using ` mvn fabric8:deploy` the deployed container only has 256m allocated. I then have to manually bump this up.

I have read the docs but could not see how to specify mem and cpu for the container - only for the cluster.

Thanks

**Comment by dipak-pawar** [comment]
You can put `deployment.yml` in `src/main/fabric8/deployment.yml` which has following content
```yaml
spec:
  template:
    spec:
      containers:
        - resources:
              requests:
                memory: 64Mi
                cpu: 250m
              limits:
                memory: 128Mi
                cpu: 500m
```

You can look for sample project here https://github.com/dipak-pawar/ftest-openshift-fabric8-maven-plugin
