### ISSUE TITLE
The ports configuration is not applied to kubernetes configs

### ISSUE THREAD

**Issue by OndraZizka** [fabric8io/fabric8-maven-plugin#1257]
### Description
I have a `pom.xml` with a Dropwizard service. I'm trying to expose the ports 9000 and 9001.

It works fine with docker-maven-plugin.

However, with FMP, I'm not able to force it to generate Kubernetes configs with these ports.
Here's what I have in the FMP's `<configuration>`:

                                <image>
                                    <alias>csa</alias>
                                    <name>collab/csa</name>
                                    <registry>${collab.docker.registry}</registry>
                                    <build>
                                        ...
                                        <ports>  <port>9000</port> <port>9001</port> </ports>
                                    </build>
                                    <run>
                                        <namingStrategy>alias</namingStrategy>
                                        <dependsOn>csl-entities-csa</dependsOn>
                                        <ports>
                                            <port>port.csaApp:9000</port>
                                            <port>port.csaAdmin:9001</port>
                                        </ports>
                                        ...
                                    </run>

This didn't work, so I have added:

                            <enricher>
                                <config>
                                    <fmp-service>
                                        <name>csa-service</name>
                                        <type>NodePort</type>
                                        <multiPort>true</multiPort>
                                        <port>9000:9000,9001:9001</port>
                                    </fmp-service>
                                </config>
                            </enricher>

Still, what I get doesn't contain these ports anywhere:  

* `csa-application/target/classes/META-INF/fabric8/kubernetes/csa-application-deployment.yml`:

```
spec:
    ...
  template:
    ...
   spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: csa/csa-application:snapshot-180328-111653-0867
        imagePullPolicy: IfNotPresent
        name: java-exec
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
```

* `csa-application/target/classes/META-INF/fabric8/kubernetes/csa-application-svc.yml`:

```
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
```
I haven't found other places in the documentation to change the ports, so I assume the config isn't applied.

I can add the pom.xml if needed.

### Info

* f-m-p version : 3.5.38
* Maven version (`mvn -v`) :
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /sw/prog/maven-3.5.0
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /sw/prog/jdk/1.8.0_144/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-37-generic", arch: "amd64", family: "unix"
```
* Kubernetes / OpenShift setup and version :  minikube version: v0.25.0
