### ISSUE TITLE
The configured resource labels are not applied 

### ISSUE THREAD

**Issue by OndraZizka** [fabric8io/fabric8-maven-plugin#1258]
### Description
The labels do not appear in the config files.  
If I put this to the configuration:
```
<labels><all>
  <foo>bar<foo>
  <group>mygroup<group>
</all></labels>
```

Then the resources have no trace of  these labels:

```
  kind: Deployment
    labels:
      app: csa-application
      provider: fabric8
      version: X.2.0-SNAPSHOT
      group: com.blackboard.collaborate.csa

  kind: Service
    labels:
      expose: "true"
      app: csa-application
      provider: fabric8
      version: X.2.0-SNAPSHOT
      group: com.blackboard.collaborate.csa
```

### Info

* f-m-p version : 3.5.38
* Maven version (`mvn -v`) :
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /sw/prog/maven-3.5.0
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /sw/prog/jdk/1.8.0_144/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-37-generic", arch: "amd64", family: "unix"
```
* Kubernetes / OpenShift setup and version :  minikube version: v0.25.0
