### ISSUE TITLE
CronJob creation fails during fabric8:apply goal

### ISSUE THREAD

**Issue by smoyer64** [fabric8io/fabric8-maven-plugin#1271]
FMP accepts a manifest (or template) for a ``kind: CronJob`` but fails to deploy it to the Kubernetes cluster.  Apparently the kubernetes-client library used by FMP doesn't support ``CronJob`` yet, so while FMP processes it, pushing it to the cluster causes the following error:

``` (text)
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:apply (deploy) on project academics-student-importer: Failed to create CronJob from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: No handler found for object:CronJob(
<the generated manifest>), status=null, additionalProperties={}) -> [Help 1]
```

See https://github.com/fabric8io/kubernetes-client/issues/1018 for the kubernetes-client roadmap

**Comment by smoyer64** [comment]
Here's the (slightly anonymized) YAML for several of our projects:

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: application-importer
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: application-importer
            image: application-importer:${timestamp}
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: application-config
            - secretRef:
                name: application-secret
          restartPolicy: Never
```
