### ISSUE TITLE
Bogus validation errors for PVC fragments

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1279]
### Description

When using an PVC fragment like

```yml
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

the following warning/error happens:

```
[WARNING] F8: Invalid Resource : /Users/roland/Development/abi88/target/classes/META-INF/fabric8/openshift/abi88-pvc.yml
[message=.spec.resources.requests.storage: string found, object expected, violation type=type]
```

However, according to https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/ this is perfectly valid.

### Info

* f-m-p version : 3.5.38
* Kubernetes / OpenShift setup and version : OpenShift / Minishift 3.7
