### ISSUE TITLE
A DC fragment's templates labels, env, image, ... are overwritten

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1280]
### Description

When using an extra DC fragment in `src/main/fabric8` that specifies a label, like in `abi88-db-dc.yml`

```yaml
spec:
  strategy:
    type: Recreate
  replicas: 1
  spec:
    template:
      metadata:
        labels:
          component: db
      spec:
        containers:
          # MySql image
        - name: "db"
          image: "mysql:5"
          imagePullPolicy: IfNotPresent
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: secret
          - name: MYSQL_DATABASE
            value: abi88
          ports:
          - containerPort: 3306
          volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: "mysql"
            subPath: "mysql"
          resources:
            limits:
              memory: 200Mi
        volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: abi88
        triggers:
        - type: ConfigChange
```

then everything gets overwritten by the enrichers in the resulting `abi88-db-deploymentconfig.yml`:

```yaml
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: abi88
    provider: fabric8
    version: 1.3.5
    group: abi88pegnitz
  name: abi88-db
spec:
  replicas: 1
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      labels:
        app: abi88
        provider: fabric8
        version: 1.3.5
        group: abi88pegnitz
    spec:
      containers:
      - image: rhuss/abi88
        imagePullPolicy: IfNotPresent
        name: webapp
```

Note that:

* labels are overwritten
* envs are removed
* image has been exchanged
* triggers have been removed
* volumes have been removed
* ports are removed

This means, that the usage of dc fragments which are not for the module's image itself are completely useless.

### Info

* f-m-p version : 3.5.38
* Kubernetes / OpenShift setup and version : OpenShift 3.7.1
