### ISSUE TITLE
Namespace missing in generated DeploymentConfig

### ISSUE THREAD

**Issue by MarWestermann** [fabric8io/fabric8-maven-plugin#1360]
### Description
When I generate the openshift resources with `mvn clean package fabric8:build fabric8:resource` e.g. in namespace test, the generated DeploymentConfig does not contain the namespace in the image-ref.

### Info

* f-m-p version : 3.5.41
* Maven version (`mvn -v`) : 
```
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-130-generic", arch: "amd64", family: "unix"
```
* Kubernetes / OpenShift setup and version : 1 master, 4 nodes
```
openshift v3.9.0+ee4d1e7-20
kubernetes v1.9.1+a0ce1bc657
```
* If it's a bug, how to reproduce :

** login to openshift project test
** run `mvn clean package farbic8:build fabric8:resource`
** openshift.yaml has a reference to the image in the DeploymentConfig def: $.spec.template.spec.containers[0].image
```
image: my-service:latest
```

IMHO this should also reference the namespace/project where the image has been pushed to otherwise when deploying the resource to another project it won't find the image in the current namespace.

```
image:test/my-service:latest
```

**Comment by MarWestermann** [comment]
There is also a namespace missing on the generated imageChangeTrigger. While the generated deploymentconfig has the trigger set to:

```
- imageChangeParams:
      automatic: true
      containerNames:
      - vertx
      from:
        kind: ImageStreamTag
        name: magento2-auth-service:latest
    type: ImageChange
```
I would expect it to be:

```
- imageChangeParams:
      automatic: true
      containerNames:
      - vertx
      from:
        kind: ImageStreamTag
        name: magento2-auth-service:latest
        namespace: cicd
    type: ImageChange
```
I saw a code change in f-m-p where the namespace is set to image.getUser() but I am not sure how this could be set: https://github.com/rohanKanojia/fabric8-maven-plugin/commit/274deb090f3df77b2344dc8b014283f52e5610c5
