### ISSUE TITLE
Add stale-bot 

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1400]
### Description

Please add stale-bot for cleaning up stale issues.

**Comment by rhuss** [comment]
@dev-gaur I would use this config for the beginning:

```yaml
daysUntilStale: 90
daysUntilClose: 7
exemptLabels:
  - prio/p0
  - status/never-stale
staleLabel: status/stale
markComment: >
  This issue has been automatically marked as stale because it has not had any activity since 90 days. It will be closed if no further activity occurs within 7 days. Thank you for your contributions!
closeComment: false
only: issues
```
