### ISSUE TITLE
Apply updates to  the new discovery.3scale.net labels/annotations.

### ISSUE THREAD

**Issue by chirino** [fabric8io/fabric8-maven-plugin#1402]
### Description

FMP is now adding discovery.3scale.net annotations to the Services.  I see it generating services like: 

```
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 6f270919931c01502be53e4036d7bfa940bf357b
      discovery.3scale.net/discovery-version: v1
      prometheus.io/port: "9779"
      fabric8.io/iconUrl: img/icons/camel.svg
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      discovery.3scale.net/scheme: http
    labels:
      expose: "true"
      discovery.3scale.net/discoverable: "true"
      app: swagger-petstore
      provider: fabric8
      version: 1.0-SNAPSHOT
      group: io.example
    name: swagger-petstore
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: swagger-petstore
      provider: fabric8
      group: io.example
```

But it's not setting `discovery.3scale.net/port` which is now required per an update to 
https://docs.google.com/document/d/1QsunYWA9jy1VRjkIeWFUwEScSXsmaAYmuwEF1Zs5SoU/edit#
Also the label should be `discovery.3scale.net: "true"` instead of `discovery.3scale.net/discoverable: "true"`. And the `discovery.3scale.net/description-path` was also not auto set for my project.
