### ISSUE TITLE
Can't add custom kind, IngressRoute

### ISSUE THREAD

**Issue by doddatpivotal** [fabric8io/fabric8-maven-plugin#1473]
### Description
I'm trying to add a new kind: IngressRoute.  I've updated the pom.xml plugin configuration per below, and added a file called ingressroute.yml in my src/main/fabric8 directory.  However I get the following error when i do mvn fabric8:resource...

[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:4.0.0-M2:resource (default-cli) on project gs-spring-boot-docker: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:4.0.0-M2:resource failed: No resource type found for:contour.heptio.com/v1beta1#IngressRoute.

### Info
```
            <plugin>
              <groupId>io.fabric8</groupId>
              <artifactId>fabric8-maven-plugin</artifactId>
              <version>4.0.0-M2</version>
              <configuration>
                <ignoreServices>false</ignoreServices>
                <registry>${docker.image.prefix}</registry>
                <mappings>
                    <mapping>
                        <kind>IngressRoute</kind>
                        <filenameTypes>ingressroute</filenameTypes>
                    </mapping>
                </mappings>
              </configuration>
            </plugin>
```

Is there anything that you can spot that I'm doing wrong?

### ingressroute.yml
```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  labels:
    run: ${project.artifactId}
  name: ${project.artifactId}
  namespace: default
spec: 
  virtualhost:
    fqdn: ${project.artifactId}.contour.bissau-pks-cluster-2.pks.bissau.toolsmith.winterfell.live
  routes: 
    - match: /
      services: 
        - name: ${project.artifactId}
          port: 8080
```
