### ISSUE TITLE
4.0.0 is generating ImageChange triggers in the DeploymentConfig

### ISSUE THREAD

**Issue by mojsha** [fabric8io/fabric8-maven-plugin#1578]
### Description
It seems like 4.0.0 has reverted to generating ImageChange triggers for OpenShift DeploymentConfig objects with the automatic field set to true, e.g.

```
    - imageChangeParams:
        automatic: true
        containerNames:
          - sample-t-demo
        from:
          kind: ImageStreamTag
          name: 'demo:1.0.40-Stable-Release'
          namespace: sample-t
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/sample-t/demo@sha256:5a41e6403eafb57c8ffb9e6f46470d3d697171f400a44b1f2d323a14144e26bf
```

This needs to be fixed, and the flag to disable this re-introduced. 
* f-m-p version :
4.0.0

* Kubernetes / OpenShift setup and version :
3.10

* If it's a bug, how to reproduce :
mvn fabric8:resource fabric8:build fabric8:apply on a project with a DeploymentConfig

@rohanKanojia
