### ISSUE TITLE
4.0.0 is generating an unwanted sidecar copy of application instance

### ISSUE THREAD

**Issue by mojsha** [fabric8io/fabric8-maven-plugin#1579]
### Description

It looks like 4.0.0 is "auto-generating" an unwanted sidecar copy of the application instance. 

It is easiest explained using screenshots:

Using 3.5.42, the application is running in container "demo":
![image](https://user-images.githubusercontent.com/27762179/54524741-02e2de80-4973-11e9-8382-3590a19f7208.png)

Using 4.0.0, two instance of the application now are running, demo (as defined in a DC) and "demo-sample-t" (a concatenation of the DC name "demo" and namespace name "sample-t"):

![image](https://user-images.githubusercontent.com/27762179/54524800-23129d80-4973-11e9-8f34-a4c3450e6060.png)

As you can see, the "sample-t-demo" (sample-t is the name of the namespace) has been generated without any resource fragment.

### Info

* f-m-p version :
4.0.0
* Kubernetes / OpenShift setup and version :
3.10
* If it's a bug, how to reproduce :
Use a DC and upgrade to 4.0.0 and do the regular fabric8:resource fabric8:build fabric8:apply cycle. It should generate the unwanted sidecar.

@rohanKanojia

**Comment by rohanKanojia** [comment]
@mojsha : I can confirm that this is certainly a bug which needs to be fixed. This is a sideeffect of #1202 since fmp now considers container in fragment as a sidecar. We need to have some option in order to disable this autogeneration of the main container.

**Comment by rohanKanojia** [comment]
Hm, this is being done via `ControllerViaPluginConfigurationEnricher` which was earlier a part of DefaultControllerEnricher( see #401 ). You can get rid of this sidecar by excluding this enricher in your plugin configuration.

```
          <enricher>
            <includes>
              <include>fmp-portname</include>
            </includes>
            <excludes>
              <exclude>build</exclude>
              <exclude>fmp-controller</exclude>
              <exclude>fmp-controller-from-configuration</exclude>
            </excludes>
            <config>
              <f8-service>
                <type>NodePort</type>
              </f8-service>
            </config>
          </enricher>

```

**Comment by rohanKanojia** [comment]
@mojsha: Okay, so this enricher is creating two separate containers instead of one. So the idea of sidecar containers was to treat every container as sidecar whose name is not equal to default application container(which is generated by fmp). So if you take a resource fragment like this:
```
kind: "DeploymentConfig"
apiVersion: "v1"
spec:
  template: 
    spec:
      containers:
        - name: "spring-boot"
          image: "openjdk"
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 3 
```
This won't generate sidecar since container name is specified and it is equal to default application container name. But if you change container name, then it would be treated as a sidecar. For example, this resource fragment would generate two containers in resulting deploymentconfig:
```
kind: "DeploymentConfig"
apiVersion: "v1"
spec:
  template: 
    spec:
      containers:
        - name: "spring-boot2122344"
          image: "openjdk"
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 3 
```

So if container specified in resource fragment doesn't have a name or it's name is equal to default application's container name; it would not be treated as sidecar. You can manipulate fmp's default name for main container via this parameter: `fabric8.generator.alias`.

I would add it to documentation to avoid confusion in future.
