### ISSUE TITLE
Replicas fragment not set

### ISSUE THREAD

**Issue by maragao** [fabric8io/fabric8-maven-plugin#1600]
* f-m-p version : 4.0.0
In this deployment fragment:
```
spec:
  replicas: 2
  template:
    metadata:
      labels:
     ......
```
In version f-m-p 3.5.42, the generated code replicas is 2 (as expected), but in f-m-p 4.0.0 the replicas is 1. Any thoughts?
