### ISSUE TITLE
CronJob version in set to v1 instead of batch/v1beta1

### ISSUE THREAD

**Issue by Beennnn** [fabric8io/fabric8-maven-plugin#1630]
When creating a cronJob file in src/main/fabric8, the generated file uses version `v1` instead of `batch/v1beta1`: 

```
---
apiVersion: v1
kind: CronJob
metadata:
  labels:
    app: fs-connector-a3i
    provider: fabric8
    version: 1.3.0.BUILD-SNAPSHOT
    group: com.airbusds.geo.agri.fs
  name: synchronize-results
spec:
  jobTemplate:
...
```

This is due to the class KubernetesResourceUtil that does not manage cronjob files, see https://github.com/fabric8io/fabric8-maven-plugin/blob/master/core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java#L254

```
if (Objects.equals(kind, "Ingress")) {
  apiVersion = apiVersions.getExtensionsVersion();
} else if (Objects.equals(kind, "StatefulSet") || Objects.equals(kind, "Deployment")) {
  apiVersion = apiVersions.getAppsVersion();
 } else if (Objects.equals(kind, "Job")) {
  apiVersion = apiVersions.getJobVersion();
} else if (Objects.equals(kind, "DeploymentConfig") && platformMode == PlatformMode.openshift) {
  apiVersion = apiVersions.getOpenshiftV1version();
}
```

I suggest adding a new use case:
```
} else if (Objects.equals(kind, "CronJob"){
  apiVersion = apiVersions.getCronJobVersion();
}
```
And adding a new property for CronJob in ResourceVersioning with value "ResourceVersioning".
