### ISSUE TITLE
Support Auth with registry.redhat.io

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-maven-plugin#1637]
## Feature request

Support [Auth with registry.redhat.io](https://access.redhat.com/RegistryAuthentication). The new Red Hat registry requires to be authenticated to download RHEL8 UBI images such as [Java OpenJDK11](https://access.redhat.com/containers/?tab=images#/registry.access.redhat.com/openjdk/openjdk-11-rhel7)

By consequence it is needed to perform a : 

- `docker login` step in order to pull the docker image or 
- to use a generated [token](https://access.redhat.com/terms-based-registry/) that we could use using a `imagePullSecrets` field added to the DeploymentConfig or PodSpec

**Comment by cmoulliard** [comment]
I created a template to experiment successfully the token approach with a source to image build

```
apiVersion: v1
kind: Template
metadata:
  name: spring-boot-rest-http
  annotations:
    iconClass: icon-spring
    tags: spring-boot, rest, java, microservice
    openshift.io/display-name: Spring Boot - REST Http Endpoint
    openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/documentation-url: "https://appdev.prod-preview.openshift.io/docs/spring-boot-runtime.html#mission-http-api-spring-boot-tomcat"
    description: >-
      The REST API Level 0 Mission provides a basic example of mapping business operations to a remote procedure call endpoint over HTTP using a REST framework.
parameters:
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: S2I_SOURCE_DEPLOYMENTS_FILTER
  description: To specify artifact type
  value: '*.jar'
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
- name: MAVEN_MIRROR_URL
  description: Maven Nexus Repository to be used during build phase
  displayName:
  required: false
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: 10977452-snowdrop-pull-secret
  data:
    .dockerconfigjson: REMOVED,REMOVED,REMOVED
  type: kubernetes.io/dockerconfigjson
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: spring-boot-rest-http
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime
  spec:
    tags:
    - name: "latest"
      from:
        kind: DockerImage
        name: registry.redhat.io/openjdk/openjdk-11-rhel8
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: spring-boot-rest-http
    name: spring-boot-rest-http
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'spring-boot-rest-http:2.1.3-1'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'runtime:latest'
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
        - name: MAVEN_MIRROR_URL
          value: "${MAVEN_MIRROR_URL}"
        - name: S2I_SOURCE_DEPLOYMENTS_FILTER
          value: "${S2I_SOURCE_DEPLOYMENTS_FILTER}"
      type: Source
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: spring-boot-rest-http
      provider: snowdrop
      version: "2.1.3-1"
      group: io.openshift.booster
    name: spring-boot-rest-http
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: spring-boot-rest-http
      provider: snowdrop
      group: io.openshift.booster
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: spring-boot-rest-http
      provider: snowdrop
      version: "2.1.3-1"
      group: io.openshift.booster
    name: spring-boot-rest-http
  spec:
    replicas: 1
    selector:
      app: spring-boot-rest-http
      provider: snowdrop
      group: io.openshift.booster
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: spring-boot-rest-http
          provider: snowdrop
          version: "2.1.3-1"
          group: io.openshift.booster
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: spring-boot-rest-http:2.1.3-1
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 180
          securityContext:
            privileged: false
        imagePullSecrets:
          - name: 10977452-snowdrop-pull-secret
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: spring-boot-rest-http:2.1.3-1
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: spring-boot-rest-http
      provider: snowdrop
      version: "2.1.3-1"
      group: io.openshift.booster
    name: spring-boot-rest-http
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: spring-boot-rest-http
```
