### ISSUE TITLE
An extra container is created if the container name is not spring-boot

### ISSUE THREAD

**Issue by shawkins** [fabric8io/fabric8-maven-plugin#1641]
### Description
With the spring generator using a deployment config fragment, if the container name is not named spring-boot the generated deployment config will have two containers one with the name from the fragment and the other with the name of spring-boot.  The extra spring-boot container is not valid and will cause the deployment to fail.

### Info

* f-m-p version : 4.1.0
* Maven version (`mvn -v`) : 3.5.3

See https://github.com/teiid/teiid-openshift-examples/tree/180902725846bc128839cba08c1a1456468f194f - it works as expected with f-m-p 3.5.41 which is defined in the parent pom, but will fail with 4.1.0.

If I change:

```
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
...
    spec:
      containers:
      - name: ${project.artifactId}
```
To:

```
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
...
    spec:
      containers:
      - name: spring-boot
```
It will work with 4.1.0
