### ISSUE TITLE
mvn fabric8:resource converts types of kubernetes YAML annotations in fragment

### ISSUE THREAD

**Issue by nimish** [fabric8io/fabric8-maven-plugin#1714]
### Info

* f-m-p version : 4.2.0
* Maven version (`mvn -v`) : 3.6.2
```
metadata:
  annotations:
    # Enable client certificate authentication
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'

```

After doing whatever it does to an ingress resource fragment (taken from the nginx ingress controller examples), the f-m-p will emit:

```
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: on

```

Note the lack of quotes. This results in the warning:

`[message=.metadata.annotations.nginx.ingress.kubernetes.io/auth-tls-verify-client: boolean found, string expected, violation type=type]`

The difference matters quite a bit as the wrong type will stop the ingress controller from actually enforcing client certificate auth...
