### ISSUE TITLE
Unable to define environment variable and mount a secret at the same time

### ISSUE THREAD

**Issue by mrs-miracle** [fabric8io/fabric8-maven-plugin#1729]
### Description

I have deployment.yaml file where I define an environment variable and mount a secret into the container, but I get error below when trying to deploy the resources. Only defining one of the items, variable or volume mount, works fine. My application is a Spring Boot app.

deployment.yaml
```
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: ${project.artifactId}
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: truststore
          secret:
            secretName: ${project.artifactId}
      containers:
        - volumeMounts:
            - name: truststore
              mountPath: /deployments/truststore
              readOnly: true
        - env:
            - name: JAVA_OPTS
              value: "-DFOO=true -Dbar=false"
```

Error message from fabric8:deploy:
```
[ERROR] F8: Failed to update DeploymentConfig from openshift.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://192.168.64.3:8443/apis/apps.openshift.io/v1/namespaces/jobcrawler/deploymentconfigs/jobcrawler. Message: DeploymentConfig.apps.openshift.io "jobcrawler" is invalid: [spec.template.spec.containers[1].name: Required value, spec.template.spec.containers[1].image: Required value]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.template.spec.containers[1].name, message=Required value, reason=FieldValueRequired, additionalProperties={}), StatusCause(field=spec.template.spec.containers[1].image, message=Required value, reason=FieldValueRequired, additionalProperties={})], group=apps.openshift.io, kind=DeploymentConfig, name=jobcrawler, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=DeploymentConfig.apps.openshift.io "jobcrawler" is invalid: [spec.template.spec.containers[1].name: Required value, spec.template.spec.containers[1].image: Required value], metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).. DeploymentConfig(apiVersion=apps.openshift.io/v1, kind=DeploymentConfig, metadata=ObjectMeta(annotations={configmap.fabric8.io/update-on-change=jobcrawler, fabric8.io/git-commit=9278b435c0d418e13d581c3532cdf57d56927c68, fabric8.io/git-branch=master}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={app=jobcrawler, provider=fabric8, version=0.0.1-SNAPSHOT, group=com.example}, managedFields=[], name=jobcrawler, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=DeploymentConfigSpec(minReadySeconds=null, paused=null, replicas=1, revisionHistoryLimit=2, selector={app=jobcrawler, provider=fabric8, group=com.example}, strategy=DeploymentStrategy(activeDeadlineSeconds=null, annotations=null, customParams=null, labels=null, recreateParams=null, resources=null, rollingParams=RollingDeploymentStrategyParams(intervalSeconds=null, maxSurge=null, maxUnavailable=null, post=null, pre=null, timeoutSeconds=3600, updatePeriodSeconds=null, additionalProperties={}), type=Rolling, additionalProperties={}), template=PodTemplateSpec(metadata=ObjectMeta(annotations={fabric8.io/git-commit=9278b435c0d418e13d581c3532cdf57d56927c68, configmap.fabric8.io/update-on-change=jobcrawler, fabric8.io/git-branch=master}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={app=jobcrawler, provider=fabric8, version=0.0.1-SNAPSHOT, group=com.example}, managedFields=[], name=null, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, affinity=null, automountServiceAccountToken=null, containers=[Container(args=[], command=[], env=[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=metadata.namespace, additionalProperties={}), resourceFieldRef=null, secretKeyRef=null, additionalProperties={}), additionalProperties={})], envFrom=[], image=jobcrawler:latest, imagePullPolicy=IfNotPresent, lifecycle=null, livenessProbe=null, name=spring-boot, ports=[ContainerPort(containerPort=8080, hostIP=null, hostPort=null, name=http, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=9779, hostIP=null, hostPort=null, name=prometheus, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=8778, hostIP=null, hostPort=null, name=jolokia, protocol=TCP, additionalProperties={})], readinessProbe=null, resources=null, securityContext=SecurityContext(allowPrivilegeEscalation=null, capabilities=null, privileged=false, procMount=null, readOnlyRootFilesystem=null, runAsGroup=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, windowsOptions=null, additionalProperties={}), stdin=null, stdinOnce=null, terminationMessagePath=null, terminationMessagePolicy=null, tty=null, volumeDevices=[], volumeMounts=[VolumeMount(mountPath=/deployments/truststore, mountPropagation=null, name=truststore, readOnly=true, subPath=null, subPathExpr=null, additionalProperties={})], workingDir=null, additionalProperties={}), Container(args=[], command=[], env=[EnvVar(name=JAVA_OPTS, value=-DFOO=true -Dbar=false, valueFrom=null, additionalProperties={})], envFrom=[], image=null, imagePullPolicy=null, lifecycle=null, livenessProbe=null, name=null, ports=[], readinessProbe=null, resources=null, securityContext=null, stdin=null, stdinOnce=null, terminationMessagePath=null, terminationMessagePolicy=null, tty=null, volumeDevices=[], volumeMounts=[], workingDir=null, additionalProperties={})], dnsConfig=null, dnsPolicy=null, enableServiceLinks=null, hostAliases=[], hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], initContainers=[], nodeName=null, nodeSelector=null, preemptionPolicy=null, priority=null, priorityClassName=null, readinessGates=[], restartPolicy=null, runtimeClassName=null, schedulerName=null, securityContext=null, serviceAccount=null, serviceAccountName=null, shareProcessNamespace=null, subdomain=null, terminationGracePeriodSeconds=null, tolerations=[], volumes=[Volume(awsElasticBlockStore=null, azureDisk=null, azureFile=null, cephfs=null, cinder=null, configMap=null, csi=null, downwardAPI=null, emptyDir=null, fc=null, flexVolume=null, flocker=null, gcePersistentDisk=null, gitRepo=null, glusterfs=null, hostPath=null, iscsi=null, name=truststore, nfs=null, persistentVolumeClaim=null, photonPersistentDisk=null, portworxVolume=null, projected=null, quobyte=null, rbd=null, scaleIO=null, secret=SecretVolumeSource(defaultMode=null, items=[], optional=null, secretName=jobcrawler, additionalProperties={}), storageos=null, vsphereVolume=null, additionalProperties={})], additionalProperties={}), additionalProperties={}), test=null, triggers=[DeploymentTriggerPolicy(imageChangeParams=null, type=ConfigChange, additionalProperties={})], additionalProperties={}), status=null, additionalProperties={}): io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://192.168.64.3:8443/apis/apps.openshift.io/v1/namespaces/jobcrawler/deploymentconfigs/jobcrawler. Message: DeploymentConfig.apps.openshift.io "jobcrawler" is invalid: [spec.template.spec.containers[1].name: Required value, spec.template.spec.containers[1].image: Required value]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.template.spec.containers[1].name, message=Required value, reason=FieldValueRequired, additionalProperties={}), StatusCause(field=spec.template.spec.containers[1].image, message=Required value, reason=FieldValueRequired, additionalProperties={})], group=apps.openshift.io, kind=DeploymentConfig, name=jobcrawler, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=DeploymentConfig.apps.openshift.io "jobcrawler" is invalid: [spec.template.spec.containers[1].name: Required value, spec.template.spec.containers[1].image: Required value], metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
```

DeploymentConfig generated in target/classes/META-INF/fabric8/openshift.yaml
```
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "jobcrawler:latest"
          imagePullPolicy: "IfNotPresent"
          name: "spring-boot"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          - containerPort: 9779
            name: "prometheus"
            protocol: "TCP"
          - containerPort: 8778
            name: "jolokia"
            protocol: "TCP"
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: "/deployments/truststore"
            name: "truststore"
            readOnly: true
        - env:
          - name: "JAVA_OPTS"
            value: "-DFOO=true -Dbar=false"
        volumes:
        - name: "truststore"
          secret:
            secretName: "jobcrawler"
```
### Info

* f-m-p version : 4.3.0
* Maven version (`mvn -v`) : 3.6.2
* Kubernetes / OpenShift setup and version : OpenShift 3.11.104 in Minishift
