### ISSUE TITLE
No way to set build config memory/CPU request and limi

### ISSUE THREAD

**Issue by jflefebvre06** [fabric8io/fabric8-maven-plugin#1770]
#1604 # Description
Could you please add a way to set resources configuration for buildConfig like

```
apiVersion: "v1"
kind: "BuildConfig"
metadata:
  name: "sample-build"
spec:
  resources:
    limits:
      cpu: "100m" 
      memory: "256Mi"
```

### Info
I'm using openshift, my build is OOM killed due to 250Mi memory limit ranges

```
spec:
  limits:
    - type: Pod
      max:
        cpu: '4'
        memory: 4Gi
      min:
        cpu: 10m
        memory: 3Mi
    - type: Container
      max:
        cpu: '4'
        memory: 4Gi
      min:
        cpu: 10m
        memory: 3Mi
      default:
        cpu: 100m
        memory: 250Mi
      defaultRequest:
        cpu: 10m
        memory: 10Mi
```
