### ISSUE TITLE
imagePullSecrets

### ISSUE THREAD

**Issue by hlavki** [fabric8io/fabric8-maven-plugin#1790]
# Description
Volumes are not generated from xml configuration when `deployment.yml` is present.
Let's say I have `src/main/fabric8/deployment.yml`
```yml
spec:
  template:
    spec:
      imagePullSecrets:
      - name: secret-name
```
And pom.xml contains:
```xml
<configuration>
    <resources>
        <volumes>
            <volume>
                <name>service-account</name>
                <type>secret</type>
                <secretName>codelist-service-account</secretName>
                <mounts>
                    <mount>/etc/google</mount>
                </mounts>
            </volume>
        </volumes>
    </resources>
</configuration>
```
then kubernetes.yml is generated without volumes. But when I delete `deployment.yml` then volumes are generated properly:

```yml
          volumeMounts:
          - mountPath: /etc/google
            name: service-account
            readOnly: false
        volumes:
        - name: service-account
          secret:
            secretName: codelist-service-account
```

### Info

* f-m-p version : 4.4.0
* Maven version (`mvn -v`) : 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache/apache-maven
Java version: 13.0.2, vendor: Oracle Corporation, runtime: /usr/java/jdk-13.0.2
Default locale: sk_SK, platform encoding: UTF-8
OS name: "linux", version: "5.5.2-1-default", arch: "amd64", family: "unix"
```
