### ISSUE TITLE
Liveness and readiness TCP ports are not serialized as numbers when defined as numbers

### ISSUE THREAD

**Issue by guiliguili** [fabric8io/fabric8-maven-plugin#1830]
### Description
When specifying liveness and readiness TCP port in `pom.xml` using a number value as follow :

```xml
                        [...]
                        <readiness>
                            <tcpPort>8080</tcpPort>
                        </readiness>
                        <liveness>
                            <tcpPort>8080</tcpPort>
                        </liveness>
                        [...]
```

The generated deployment file is serialized as a string value between double-quotes :

```yml
        [...]
        livenessProbe:
          tcpSocket:
            port: "8080"
        readinessProbe:
          tcpSocket:
            port: "8080"
        [...]
```

### Info

* f-m-p version : 4.4.1
* Maven version (`mvn -v`) : 3.8.3 
* Kubernetes / OpenShift setup and version : N/A
* If it's a bug, how to reproduce : c.f. steps above

### Root cause analysis

The [io.fabric8.maven.core.handler.ProbeHandler#getTCPSocketAction](https://github.com/fabric8io/fabric8-maven-plugin/blob/4beae533a97571ddd6a6bc5dfa37c56a028cd3a9/core/src/main/java/io/fabric8/maven/core/handler/ProbeHandler.java#L103) method is missing a `portObj.setKind(0)` to be compliant with `io.fabric8.kubernetes.api.model.IntOrString.Serializer`
