### ISSUE TITLE
No simple way to name container ports

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/fabric8-maven-plugin#290]
Generated ports look like:
```
ports:                                                                
- containerPort: 8080                                                 
  protocol: "TCP"                                                     
- containerPort: 9779                                                 
  protocol: "TCP"                                                     
- containerPort: 8778                                                 
  protocol: "TCP"
```

Named ports are really important, especially for stuff like the OpenShift console discovering Jolokia enabled containers (it works by finding ports named jolokia to link to openshift-jvm part of console).
