### ISSUE TITLE
s2i binary builds don't work inside BuildConfig's generated by the fabric8 console / forge

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#439]
as the BuildConfig is generated like this:
```
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: http://192.168.64.86:31972/gogsadmin/camelvanilla.git
    secrets: null
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: fabric8/s2i-java:1.3.4
    type: Source
```
which is not a s2i binary build.

if we force the recreate of the BC then it regenerates the BC as:
```
spec:
  output:
    to:
      kind: ImageStreamTag
      name: camelrecreatebuild:1.0.2
  source:
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: fabric8/s2i-java:1.3.4
    type: Source
```

So I'm thinking the s2i code that creates/updates/ignores the BC should be a little more smart. 

e.g. we could check if the current BC is `spec.source.type = Binary' and if not, create a new BC with a name of `${name}-s2i` and then use that instead
