### ISSUE TITLE
seems like the RC name and container name doesn't get defaulted right now if you supply a rc.yml

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#59]
e.g. I tried this rc.yml file and got errors:
```
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: fabric8:gitcontroller:latest
      serviceAccount: gitcontroller
```

I figured it'd default the `metadata.name` and `containers[0].name` values to the `${project.artifactId}` but it seems thats not the case right now
