### ISSUE TITLE
the spring-boot sample doesn't get any labels or selectors generated

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#72]
e.g. after a local build:
```
cd sample/spring-boot
mvn clean compile
cat target/classes/META-INF/fabric8/spring-boot-web-rs.yml
```
generates
```yaml
---
apiVersion: "extensions/v1beta1"
kind: "ReplicaSet"
metadata:
  name: "spring-boot-web"
spec:
  replicas: 1
  template:
    metadata: {}
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/spring-boot-web:3.0-SNAPSHOT"
        imagePullPolicy: "IfNotPresent"
        name: "fabric8-spring-boot-web"
        ports:
        - containerPort: 8080
          protocol: "TCP"
        securityContext:
          privileged: false
```
