### ISSUE TITLE
default to port 80 for exposed service ports for targetPort 8080?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#73]
we currently generate services like this for spring boot:

``` yaml

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "spring-boot-web"
spec:
  ports:
  - port: 8080
    protocol: "TCP"
    targetPort: 8080
```

if we have only 1 port its > 1000 and there's no explicit configuration I wonder if we should assume port 80? Or at least we can assume 8080 should be exposed as port 80 by default
