### ISSUE TITLE
ConfigMap data with array

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/fabric8-maven-plugin#792]
_fabric8 maven plugin goal `resource` fails to parse the yaml data with array of values_

### Description
When we have configmap with array of values for the data, the plugin resource goal fails with the following error:
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.2.15:resource (default-cli) on project bug-hunter-service: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.2.15:resource failed: Can not deserialize instance of java.lang.String out of START_ARRAY token
[ERROR] at [Source: N/A; line: -1, column: -1] (through reference chain: io.fabric8.kubernetes.api.model.ConfigMap["data"]->java.util.LinkedHashMap["elastic-search-indexes"])
```
### Info

* f-m-p version : 3.2.15
* Maven version (`mvn -v`) :
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Maven home: /usr/local/homebrew/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.2", arch: "x86_64", family: "mac"

```
* Kubernetes / OpenShift setup and version :
```
lient Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6+e569a27", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"not a git tree", BuildDate:"2016-11-12T09:26:56Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```
* If it's a bug, how to reproduce : 
   * Create a simple maven project and add f8-m-p to it 
   * add a following yaml config map to the `src/main/fabric8`
   *  
     ```
        ---
       apiVersion: "v1"
       data:
         elastic-search-service-name: "elasticsearch"
         elastic-search-service-port: "9200"
         elastic-search-indexes:
            - "logstash-*"
        hunting-interval: "10"
       kind: "ConfigMap"
       metadata: {}
       labels: {}
       name: "some-service"
    ```
   * run the maven like `mvn clean fabric8:resource`

___Please format the yaml as needed as copy paste might cause indentation issues__
