### ISSUE TITLE
StatefulSet deploy with Fabric8 Maven Plugin fails

### ISSUE THREAD

**Issue by oscerd** [fabric8io/fabric8-maven-plugin#865]
### Description
Hello,
I'm trying to deploy this statefulSet.yml file but it doesn't seem to work.

### Info
```yaml
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: gcr.io/google-samples/cassandra:v12
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
           cpu: "500m"
           memory: 1Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "PID=$(pidof java) && kill $PID && while ps -p $PID > /dev/null; do sleep 1; done"]
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra.default.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "K8Demo"
          - name: CASSANDRA_DC
            value: "DC1-K8Demo"
          - name: CASSANDRA_RACK
            value: "Rack1-K8Demo"
          - name: CASSANDRA_AUTO_BOOTSTRAP
            value: "false"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /ready-probe.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
        # These volume mounts are persistent. They are like inline claims,
        # but not exactly because the names need to match exactly one of
        # the stateful pod volumes.
        volumeMounts:
        - name: cassandra-data
          mountPath: /cassandra_data
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  # do not use these in production until ssd GCEPersistentDisk or other ssd pd
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
      annotations:
        volume.beta.kubernetes.io/storage-class: fast
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

This is the Yaml file from 

https://github.com/kubernetes/kubernetes/blob/master/examples/storage/cassandra/cassandra-statefulset.yaml

the error I get is the following:

```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.2.28:deploy (default-cli) on project cassandra: Failed to create StatefulSet from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: No handler found for object:StatefulSet(apiVersion=apps/v1beta1, kind=StatefulSet, metadata=ObjectMeta(annotations={fabric8.io/git-commit=a395c4c65d14091b007f023a39fade9f59867526, fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=cassandra&var-version=2.2-SNAPSHOT, fabric8.io/scm-con-url=scm:git:git@github.com:fabric8io/fabric8-ipaas.git/cassandra, fabric8.io/scm-url=http://github.com/fabric8io/fabric8-ipaas/cassandra, fabric8.io/iconUrl=https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/cassandra/src/main/fabric8/icon.png, fabric8.io/git-branch=statefulset-cassandra, fabric8.io/scm-devcon-url=scm:git:git@github.com:fabric8io/fabric8-ipaas.git/cassandra, fabric8.io/scm-tag=fabric8-ipaas-2.0.1}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={provider=fabric8, project=cassandra, version=2.2-SNAPSHOT, group=io.fabric8.ipaas.apps}, name=cassandra, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=StatefulSetSpec(replicas=3, selector=LabelSelector(matchExpressions=[], matchLabels={project=cassandra, provider=fabric8, group=io.fabric8.ipaas.apps}, additionalProperties={}), serviceName=cassandra, template=PodTemplateSpec(metadata=ObjectMeta(annotations=null, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={app=cassandra, provider=fabric8, project=cassandra, version=2.2-SNAPSHOT, group=io.fabric8.ipaas.apps}, name=null, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[Container(args=[], command=[], env=[EnvVar(name=MAX_HEAP_SIZE, value=512M, valueFrom=null, additionalProperties={}), EnvVar(name=HEAP_NEWSIZE, value=100M, valueFrom=null, additionalProperties={}), EnvVar(name=CASSANDRA_SEEDS, value=cassandra-0.cassandra.default.svc.cluster.local, valueFrom=null, additionalProperties={}), EnvVar(name=CASSANDRA_CLUSTER_NAME, value=K8Demo, valueFrom=null, additionalProperties={}), EnvVar(name=CASSANDRA_DC, value=DC1-K8Demo, valueFrom=null, additionalProperties={}), EnvVar(name=CASSANDRA_RACK, value=Rack1-K8Demo, valueFrom=null, additionalProperties={}), EnvVar(name=CASSANDRA_AUTO_BOOTSTRAP, value=false, valueFrom=null, additionalProperties={}), EnvVar(name=POD_IP, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=status.podIP, additionalProperties={}), resourceFieldRef=null, secretKeyRef=null, additionalProperties={}), additionalProperties={})], image=gcr.io/google-samples/cassandra:v12, imagePullPolicy=Always, lifecycle=Lifecycle(postStart=null, preStop=Handler(exec=ExecAction(command=[/bin/sh, -c, PID=$(pidof java) && kill $PID && while ps -p $PID > /dev/null; do sleep 1; done], additionalProperties={}), httpGet=null, tcpSocket=null, additionalProperties={}), additionalProperties={}), livenessProbe=null, name=cassandra, ports=[ContainerPort(containerPort=7000, hostIP=null, hostPort=null, name=intra-node, protocol=null, additionalProperties={}), ContainerPort(containerPort=7001, hostIP=null, hostPort=null, name=tls-intra-node, protocol=null, additionalProperties={}), ContainerPort(containerPort=7199, hostIP=null, hostPort=null, name=jmx, protocol=null, additionalProperties={}), ContainerPort(containerPort=9042, hostIP=null, hostPort=null, name=cql, protocol=null, additionalProperties={})], readinessProbe=Probe(exec=ExecAction(command=[/bin/bash, -c, /ready-probe.sh], additionalProperties={}), failureThreshold=null, httpGet=null, initialDelaySeconds=15, periodSeconds=null, successThreshold=null, tcpSocket=null, timeoutSeconds=5, additionalProperties={}), resources=ResourceRequirements(limits={cpu=Quantity(amount=500m, format=null, additionalProperties={}), memory=Quantity(amount=1Gi, format=null, additionalProperties={})}, requests={cpu=Quantity(amount=500m, format=null, additionalProperties={}), memory=Quantity(amount=1Gi, format=null, additionalProperties={})}, additionalProperties={}), securityContext=SecurityContext(capabilities=Capabilities(add=[IPC_LOCK], drop=[], additionalProperties={}), privileged=null, readOnlyRootFilesystem=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, additionalProperties={}), stdin=null, stdinOnce=null, terminationMessagePath=null, tty=null, volumeMounts=[VolumeMount(mountPath=/cassandra_data, name=cassandra-data, readOnly=null, subPath=null, additionalProperties={})], workingDir=null, additionalProperties={})], dnsPolicy=null, hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], nodeName=null, nodeSelector=null, restartPolicy=null, securityContext=null, serviceAccount=null, serviceAccountName=null, subdomain=null, terminationGracePeriodSeconds=null, volumes=[], additionalProperties={}), additionalProperties={}), volumeClaimTemplates=[PersistentVolumeClaim(apiVersion=v1, kind=PersistentVolumeClaim, metadata=ObjectMeta(annotations={volume.beta.kubernetes.io/storage-class=fast}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={provider=fabric8, project=cassandra, version=2.2-SNAPSHOT, group=io.fabric8.ipaas.apps}, name=cassandra-data, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PersistentVolumeClaimSpec(accessModes=[ReadWriteOnce], resources=ResourceRequirements(limits=null, requests={storage=Quantity(amount=1Gi, format=null, additionalProperties={})}, additionalProperties={}), selector=null, volumeName=null, additionalProperties={}), status=null, additionalProperties={})], additionalProperties={}), status=null, additionalProperties={}) -> [Help 1]
```

* f-m-p version : 
3.2.28
* Maven version (`mvn -v`) : 
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.8.0_65/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-327.36.3.el7.x86_64", arch: "amd64", family: "unix"

* Kubernetes / OpenShift setup and version : minikube 0.17.1
* If it's a bug, how to reproduce : you can use the https://github.com/fabric8io/fabric8-ipaas/tree/master/cassandra ipaas image and replace the deployment.yaml file with the statefulSet file above. Then run mvn fabric8:deploy
