### ISSUE TITLE
Introduce "extends" for profiles

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#886]
would be nice if profiles could extend another profile to avoid repetition e.g. of generators if the profile is only about including certain enrichers.

E.g. for a profile like

```
- name: minimal
   extends: default
   enricher:
     includes:
     - fmp-name
     - fmp-controller
     - fmp-service
     - fmp-image
     - fmp-project
     - fmp-debug
```

one then wouldn't need to repeat all generators as they are inherited from the `default` profile.
