### ISSUE TITLE
"matchLabels" section of generated kubernetes.yml always contains the version label

### ISSUE THREAD

**Issue by rrybalkin** [fabric8io/fabric8-maven-plugin#907]
### Description
Since plugin version **3.2.27** the built artifact version is always included into "matchLabels" part of kubernetes selector.  The sample below is generated by 3.2.27 plugin version:
`"selector" : {
  "matchLabels" : {
     "project" : "my-project",
     "version" : "1.0.0",
     "group" : "com.my.group"
    }
}`
It leads to the problem with rolling updates of service in kubernetes, pods with previous versions are still alive and not replaced by fresh one. We were forced to downgrade plugin to **3.2.26** version, where this problem is absent and generated selector looks like:
`"selector" : {
  "matchLabels" : {
    "project" : "my-project",
    "group" : "com.my.group"
  }
}`
That solves rolling updates problem, but prevents us from any plugin updates, which is not good. Could you please make a fix for that problem or provide any suggestion how to avoid version label placing inside selector?
### Info

* Suffered f-m-p version :  3.2.27
* Working f-m-p version : 3.2.26

```
```
* Kubernetes / OpenShift setup and version : Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
* How to reproduce : Build the project by plugin version 3.2.27 and look into generated fabric8/kubernetes.yml, _kind: Deployment, section spec.selector.matchLabels_

**Comment by rhuss** [comment]
Thanks for the report, I could reproduce this and am working on a fix.

(sorry for the delay !)

**Comment by rrybalkin** [comment]
Thanks @rhuss 
What version can we expect with that fix?

**Comment by rhuss** [comment]
@rrybalkin its in 3.4.1 which just has been released.

**Comment by thlaegler** [comment]
Hi! We face a similar problem.
Although we disabled ALL enrichers and ALL generators, the fabric8 maven plugin adds "spec.selector: {}" (with empty curly brackets) to my Kubernetes Deployment and then cries about "empty selector is not valid for deployment". Could that be related to this issue? In older versions fabric8 didn't add this empty brackets.

config-daemon-deployment.yaml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-daemon
  namespace: services
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config-daemon
    spec:
      containers:
      - name: config-daemon
        image: config-daemon:0.0.1-SNAPSHOT
        ports:
        - name: rest
          containerPort: 8888
```

After fabric8:resource:
```
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: config-daemon
    namespace: services
  spec:
    replicas: 1
    selector: {}
    template:
      metadata:
        labels:
          app: config-daemon
      spec:
        containers:
          image: config-daemon:0.0.1-SNAPSHOT
          name: config-daemon
          ports:
          - containerPort: 8888
            name: rest
```

Whats wrong? Any help is highly appreciated!
