### ISSUE TITLE
ImageStream triggers break DeploymentConfigs on OpenShift 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#943]
it seems moving to 3.4.0 of fmp adds mandatory `ImageStreamChange` triggers OOTB to `DeploymentConfig` which breaks them massively on OpenShift:

* using `oc apply`, `mvn fabric8:deploy` or `gofabric8 deploy` results in nothing being deployed at all. You have to then manually go into each DC and trigger it (e.g. via the `Deploy` button in the OpenShift console
* `oc edit dc foo` no longer updates the DC at all ;)

i.e. the DCs become pretty much utterly useless! :) 

So adding `ImageStreamChange` triggers OOTB sounds kinda scary. So lets at least make them optional for now (maybe defaulting to disabled to reduce breaking things?)

I wonder what the logic should be to ever include them since it seems to break things. Maybe we only enable them if we know that we are building the container image itself via an image stream? In my use case (the upstream fabric8 project) the images are public docker hub images and so are not built via ImageStreams

**Comment by rhuss** [comment]
@jstrachan Do you have an idea _why_ it breaks? The triggers are added since 10 months, so it's not about the latest release. I really would love to understand the reason why it breaks now.

**Comment by jstrachan** [comment]
I've no idea - I remember we had this issue a while back the last time image stream triggers crept in. 

Note that we've not seen any ImageChangeTriggers in previous releases - its 3.4.0 that this started happening again.

e.g. here's a release from a couple of weeks ago - no image change triggers: http://central.maven.org/maven2/io/fabric8/online/packages/fabric8-online-jenkins/1.0.140/fabric8-online-jenkins-1.0.140-openshift.yml

**Comment by rhuss** [comment]
Ok, let me do some forensics (because as on a first glance it seems that this code was there already for quite some time, much before this release). Maybe it was removed and reentered again (also have to check what this `containerToImageMap` is for.

**Comment by rhuss** [comment]
I just rebuild fabric8-online-jenkins with fmp 3.4.0 and I get no ImageChange triggers on the DeploymentConfig:

```
grep -C 3 triggers packages/fabric8-online-jenkins/target/classes/META-INF/fabric8/openshift.yml
```

```yaml
        - name: content
          persistentVolumeClaim:
            claimName: content-repository
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
--
--
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: LimitRange
```

Do you have a working example where this breaks for you ?

**Comment by jstrachan** [comment]
try https://github.com/fabric8io/fabric8-platform which is where I spotted the issue. e.g. https://github.com/fabric8io/fabric8-platform/tree/master/apps/configmapcontroller

**Comment by jstrachan** [comment]
ah I think fabric8-online-jenkins gets the `DeploymentConfig` from mvn dependencies, sorry about that example ;)

**Comment by rhuss** [comment]
ok, thanks :)

**Comment by rhuss** [comment]
hmm. still not:

```
[INFO] --- fabric8-maven-plugin:3.4.0:resource (fmp) @ distro ---
[WARNING] F8: Cannot access cluster for detecting mode: Failed to connect to /192.168.99.100:8443
[INFO] F8: Running in Kubernetes mode
[INFO]
....
grep -C 3 triggers apps/configmapcontroller/target/classes/META-INF/fabric8/openshift.yml
```

```yml
          image: fabric8/configmapcontroller:2.3.7
          name: configmapcontroller
        serviceAccountName: configmapcontroller
    triggers:
    - type: ConfigChange
```

But I see when I run it with `-Dfabric8.mode=openshift` I get 

```yml
         image: fabric8/configmapcontroller:2.3.7
          name: configmapcontroller
        serviceAccountName: configmapcontroller
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - configmapcontroller
        from:
          kind: ImageStreamTag
          name: configmapcontroller:2.3.7
      type: ImageChange
```

This is indeed a real issue that the created resources *must not depend* on the `fabric8.mode` as we always create both, kubernetes.yml and openshift.yml, regardless of the fabric8.mode (and so must be of course create the same descriptors in both cases).

Could it be that you did you previous builds not in an openshift cluster but in an kubernetes cluster ?

however, will investigate further ...
