### ISSUE TITLE
Generators - not honouring JAVA_OPTIONS

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/fabric8-maven-plugin#957]
f### Description
The  generators is not honouring the `JAVA_OPTIONS` that are passed as part of the resource fragments `deployment.yml` if the generator classes overrides the `getExtraJavaOptions` method and add some options via it.

Sample deployment.yml

```
---
spec:
  replicas: ${replicas}
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: "-Xms128m -Xmx512m -Djava.net.preferIPv4Stack=true"
        - name: OPENSHIFT_KUBE_PING_LABELS
          value: "project=${project.artifactId}"
        - name: OPENSHIFT_KUBE_PING_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
```
### Info

* f-m-p version : 3.4.1
* Maven version (`mvn -v`) : 3.5.0
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T01:09:06+05:30)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"
```
* Kubernetes / OpenShift setup and version : minishift v1.0.0
* Sample project : *https://github.com/kameshsampath/the-deploy-master/tree/master/demo-vertx*
