### ISSUE TITLE
Kubernetes affinity rules are ignored

### ISSUE THREAD

**Issue by camilocot** [fabric8io/fabric8-maven-plugin#959]
### Description
When Kubernetes affinity rules are included in the resource fragments, the plugin removes them from the generated manifests.

### Info

* f-m-p version : 3.4.1
* Maven version (`mvn -v`) : 3.3.9
```
Apache Maven 3.3.9 (NON-CANONICAL_2016-07-01T11:53:38Z_mockbuild; 2016-07-01T13:53:38+02:00)
Maven home: /usr/share/maven
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_101/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.10.15-200.fc25.x86_64", arch: "amd64", family: "unix"

```
* Kubernetes / OpenShift setup and version : kubernetes 1.6.4

deployment.yml fragment:
```
apiVersion: apps/v1beta1
kind: Deployment
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            labelSelector:
            - matchExpressions:
              - key: project
                operator: In
                values:
                - "${project.artifactId}"
```

Generated ${project.artifactId}-deployment.yml
```
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
  ...
spec:
  replicas: 1
  selector:
  ...
  template:
    metadata:
      annotations:
      ...
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: <image>
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
        name: dev-beatrix-config-service
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
        securityContext:
          privileged: false
```

**Comment by rhuss** [comment]
@iocanel as we are create a https://github.com/fabric8io/kubernetes-client model from the YAML files, do you know whether `affinity` is supported by the client ?

**Comment by mojsha** [comment]
@rhuss @iocanel Any ideas on whether this can be fixed? This is a feature we would like to enable via resource fragments so it would be much appreciated if we could get some clarity on where the problem lies.

**Comment by iocanel** [comment]
I don't think we support, though it shouldn't be that hard to do so. 
Created https://github.com/fabric8io/kubernetes-model/issues/224

**Comment by balexx** [comment]
+1 for affinity support in the Java client

**Comment by DavidHtx** [comment]
On fabric8-maven-plugin v 3.5.38 affinity rules are now included.
Here's a fragment of my deployment.yaml:

```
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: insertNameHere
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - insertNameHere
              topologyKey: kubernetes.io/hostname
```

This issue can be closed
