### ISSUE TITLE
Security way to refer docker  registry authentication in kubernetes resource yaml/json file

### ISSUE THREAD

**Issue by yuwzho** [fabric8io/fabric8-maven-plugin#975]
### Description
When deploying an image from a private docker registry to kubernetes, creating docker registry secret has to hard code base64 encoding docker authentication in the yaml file. This is not a security way to store secrets.

A suggestion is to put the docker authentication information into maven `settings.xml`, and refer the docker id in deployment yaml file. The fabric8 maven plugin find the corresponding docker authentication and encoding it, then apply to kubernetes API. The way to configure docker authentication is also consistence with the docker maven plugin's usage. 

How about your thoughts?

e.g.
File `secrets.yml`

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mydockerkey
  namespace: default
data:
  .dockerconfigjson: ${docker.dockerId}
type: kubernetes.io/dockerconfigjson
```

File maven `settings.xml`

```xml
<server>
    <id>dockerid</id>
    <username></username>
    <password></password>
</server>
```
