### ISSUE TITLE
'optional' parameter for a configMap volume isn't supported

### ISSUE THREAD

**Issue by vgolovina** [fabric8io/fabric8-maven-plugin#985]
Hi! Seems like for now (3.5.2) the plugin doesn't allow to use '**optional**' parameter for configMaps. It just ignores it as a part of _deployment.yml_.

For example, I have the following **configMap** volume in _deployment.yml_ (using resource fragments approach):
```
     spec:
        volumes:
          - name: config
            configMap:
              name: my-service-config
              optional: true
        containers:
          - volumeMounts:
                  - name: config
                    mountPath: /etc/config
```
But as a result f8 creates:
```
    spec:
      containers:
      - image: my-service:1.0.0
        imagePullPolicy: IfNotPresent
        name: gateway
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /etc/config
          name: config
      volumes:
      - configMap:
          name: my-service-config
        name: config 
```
The same is for **configMapKeyRef** - 'optional' parameter is just omitted.

Kubernetes supports this feature (https://github.com/kubernetes/kubernetes/pull/39981) since 1.6.0, it would be great to have an ability to use it with f8 :)

**Comment by rhuss** [comment]
@iocanel It this something that the kubernetes-client support already ?

**Comment by rohanKanojia** [comment]
I think client has got dsl for a configmap volume:
```
    Volume volume = new VolumeBuilder()
      .withName("config")
      .withNewConfigMap()
      .withName("my-service-config")
      .withOptional(true)
      .endConfigMap()
      .build();
```

I tried reproducing this, I was able to see optional parameter in generated deployment.yml
**deployment.yml(resource fragment provided)**:
```
spec:
  replicas: 1
  template:
    spec:
      volumes:
          - name: config
            configMap:
              name: my-service-config
              optional: true
      containers:
        - volumeMounts:
            - name: config
              mountPath: /app/config
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
      serviceAccount: ribbon
```

**deployment.yml(generated by fmp):**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 9dd0e1535ea4ed39aa302e5e8354dee358a1df6d
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: master
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=fabric8-maven-sample-external-resources&var-version=4.0-SNAPSHOT
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/fabric8-maven-sample-external-resources
  labels:
    app: fabric8-maven-sample-external-resources
    provider: fabric8
    version: 4.0-SNAPSHOT
    group: io.fabric8
  name: fabric8-maven-sample-external-resources
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: fabric8-maven-sample-external-resources
      provider: fabric8
      group: io.fabric8
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 9dd0e1535ea4ed39aa302e5e8354dee358a1df6d
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=fabric8-maven-sample-external-resources&var-version=4.0-SNAPSHOT
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/fabric8-maven-sample-external-resources
        fabric8.io/iconUrl: img/icons/spring-boot.svg
        fabric8.io/git-branch: master
        fabric8.io/scm-tag: HEAD
      labels:
        app: fabric8-maven-sample-external-resources
        provider: fabric8
        version: 4.0-SNAPSHOT
        group: io.fabric8
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: fabric8-maven-sample-external-resources:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /app/config
          name: config
      serviceAccount: ribbon
      volumes:
      - configMap:
          name: my-service-config
          optional: true
        name: config
```

Maybe it's support got added over previous client upgrades, @vgolovina Could you please check with 3.5.41 and see if it works for you?
